package main

import (
	"fmt"
	"os"

	git "github.com/aosanya/mwanachama-backend-git"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: ddl <spec.json> [postgres|sqlite]")
		os.Exit(2)
	}
	dialect := "postgres"
	if len(os.Args) > 2 {
		dialect = os.Args[2]
	}

	s, err := git.LoadSpec(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	fmt.Printf("-- generated by cmd/ddl from %s\n", os.Args[1])
	fmt.Printf("-- module %s, domain %s, instance %s — do not edit by hand\n\n",
		s.Module, s.Domain, s.Instance)
	for _, stmt := range s.DDL(dialect) {
		fmt.Println(stmt + ";")
	}

	o, ok := s.ByRole("blob")
	if !ok {
		return
	}
	if dialect == "postgres" {
		fmt.Printf("\n-- full-text search index, applied by Provision rather than by the spec\n")
		fmt.Printf("CREATE INDEX IF NOT EXISTS %[1]s_fts_idx ON %[1]s USING GIN (%[2]s) WHERE NOT deleted;\n",
			s.TableFor(o), git.BlobFTSExpr)
	}
}
